package pesoln

/**
  * Each new term in the Fibonacci sequence is generated by adding the
  * previous two terms. By starting with 1 and 2, the first 10 terms will be:
  *
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose values
  * do not exceed four million, find the sum of the even-valued terms.
  */

object ProjectEulerTwo {
  def sumEvenFib(lim: Int): Int = {
    def loop(lim: Int, prev: Int, curr: Int, acc: Int): Int =
      if (curr > lim) acc
      else if (curr % 2 == 0) loop(lim + 1, curr, prev + curr, acc + curr)
      else loop(lim + 1, curr, prev + curr, acc)
    loop(lim, 0, 1, 0)
  }

  def main(args: Array[String]): Unit =
    println(sumEvenFib(4000000))
}